export type Match = {
  id: string,
  character1: string,
  character2: string,
  ft: string,
  status: string,
  league_id: string,
  player1_id: string,
  player2_id: string,
  player1_elo: string,
  player1_previous_elo: string,
  player2_elo: string,
  player2_previous_elo: string,
  player1_score: string,
  player2_score: string,
  player1_ragequit: string,
  player1_forfeit: string,
  player2_ragequit: string,
  player2_forfeit: string,
  player1_elo_penalty: string,
  player2_elo_penalty: string,
  comment: string,
  is_canceled: string,
  video: string,
  completed_at: Date,
  moderated_at: Date,
  updated_at: Date,
}